site_name: 'CruftEngine'
theme: 'material'
repo_name: 'GitHub'
repo_url: 'https://github.com/mjneil/CruftEngine'
markdown_extensions:
    - toc:
        permalink: '#'
pages:
- Home : 'index.md'
- Core :
    - Actor : 'cruft/core/Actor.md'
    - Component : 'cruft/core/Component.md'
    - ActorFactory : 'cruft/core/ActorFactory.md'
    - Scheduler : 'cruft/core/Scheduler.md'
    - Emitter : 'cruft/core/Emitter.md'
- Net :
    - Cache : 'cruft/net/Cache.md'
    - Loader : 'cruft/net/Loader.md'
- Math :
    - vec2 : 'cruft/math/vec2.md'
    - vec3 : 'cruft/math/vec3.md'
    - mat3 : 'cruft/math/mat3.md'
    - mat4 : 'cruft/math/mat4.md'
- Primitives : 'primitives.md'
